const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.AddInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{caught: 0},
	{Car: 0},
	{Player: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{"3DShape": 0},
	{"3DCamera": 0},
	{HitCount: 0},
	{Bullet: 0},
	{Flash: 0},
	{PiggyBillboard: 0},
	{DestroyOutsideLayout: 0},
	{Tomato: 0},
	{Keyboard: 0},
	{Fade: 0},
	{PuffBillboard: 0},
	{play: 0},
	{Text: 0},
	{Text2: 0},
	{captured: 0},
	{Text3: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	PiggyBillboard: class extends self.I3DShapeInstance {},
	Tomato: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	PuffBillboard: class extends self.I3DShapeInstance {},
	play: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {}
}